name: Label Issues

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  labelling:
    name: 'Labelling'

    runs-on: ubuntu-latest

    steps:
  
    - name: Fetch all issues
      id: issues
      shell: bash
      run: |
        issues=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
          jq -r '.[] | .number')
        echo "::set-output name=issues::$issues"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add label - Judged      
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'add-labels'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ steps.issue.outputs.issueNumber }}
        labels: 'judged'

    - name: Remove label - Under Review
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'remove-labels'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ steps.issue.outputs.issueNumber }}
        labels: 'under review'
